### PR TITLE
Added Typescript install in Readme

### PR DESCRIPTION
**Pull request by DenisCarriere**
Whenever this PR gets merged these install instructions will work.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11262

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@mourner This definition is now merged in DT.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/concaveman

**Comment by DenisCarriere** [comment]
@mourner Added the new Typescript 2.0 install method via npm.

```bash
$ npm install --save @types/concaveman
```

https://www.npmjs.com/package/@types/concaveman

**Comment by mourner** [comment]
I'd like to keep the TypeScript notice in the readme down to a minimum to make it as concise as possible. Can we cut down all the info to one short sentence?

**Comment by DenisCarriere** [comment]
@mourner I've cut down the readme to the latest way to install the typings.

Also changed the `tilebelt` readme as well.

https://github.com/mapbox/tilebelt/pull/29

**Comment by mourner** [comment]
Thanks! I made it shorter with https://github.com/mapbox/concaveman/commit/8416af3d24dbcefab231fc7f4106901dd3374295

**Pull request merged**
